### ISSUE TITLE
PartType - Sem tratamento de excecao para post com body vazio

### ISSUE THREAD

**Issue by Viniciusalopes** [acervomusical/backend#42]
![image](https://user-images.githubusercontent.com/33704906/117519812-a9d3cb80-af7b-11eb-8cd7-3942f8dab9a7.png)

![image](https://user-images.githubusercontent.com/33704906/117519831-bce69b80-af7b-11eb-828f-d11077d4c31a.png)

**Comment by lucasDEV20** [comment]
tratando

**Comment by lucasDEV20** [comment]
feito
