### ISSUE TITLE
PartType - Post sem tratamento para nome em branco

### ISSUE THREAD

**Issue by Viniciusalopes** [acervomusical/backend#44]
![image](https://user-images.githubusercontent.com/33704906/117520014-937a3f80-af7c-11eb-9ac0-d29cca9d1b6f.png)

![image](https://user-images.githubusercontent.com/33704906/117520024-a1c85b80-af7c-11eb-9869-513152be6b4b.png)

**Comment by lucasDEV20** [comment]
feito
