### ISSUE TITLE
PartType - post sem tratamento para números no campo name

### ISSUE THREAD

**Issue by Viniciusalopes** [acervomusical/backend#47]
O campo name poderá ter números mas deverá ter pelo menos uma letra.

![image](https://user-images.githubusercontent.com/33704906/117520396-6038b000-af7e-11eb-9554-d7f7072f0c15.png)

![image](https://user-images.githubusercontent.com/33704906/117520412-6e86cc00-af7e-11eb-9435-7ffa6648d6cf.png)

**Comment by lucasDEV20** [comment]
tratado
