### ISSUE TITLE
PartType - post sem tratamento para tamanho máximo em name

### ISSUE THREAD

**Issue by Viniciusalopes** [acervomusical/backend#48]
![image](https://user-images.githubusercontent.com/33704906/117520500-d89f7100-af7e-11eb-9899-4ac9024f5263.png)

![image](https://user-images.githubusercontent.com/33704906/117520494-d210f980-af7e-11eb-859c-f5f2f3ab0dc4.png)

**Comment by lucasDEV20** [comment]
tratado
