### ISSUE TITLE
PartType - post sem tratamento para valor null em name

### ISSUE THREAD

**Issue by Viniciusalopes** [acervomusical/backend#49]
![image](https://user-images.githubusercontent.com/33704906/117520554-1d2b0c80-af7f-11eb-992f-0afd0855472a.png)

![image](https://user-images.githubusercontent.com/33704906/117520567-2b792880-af7f-11eb-9657-a4e0a5f73b9a.png)

**Comment by lucasDEV20** [comment]
tratado
