### ISSUE TITLE
Media - Alterar nome da constraint

### ISSUE THREAD

**Issue by marcospaulo-paixao** [acervomusical/backend#99]
Alterar nome da constraint unique da coluna med_path da tabela media e fazer a validação da mesma caso haja duplicidade.

![image](https://user-images.githubusercontent.com/55635755/122230725-48631e80-ce90-11eb-9e33-b05f3dc1be21.png)

**Comment by Viniciusalopes** [comment]
Resolvido.
Nomeadas todas as constraints de UNIQUE e FK no backend.
